### ISSUE TITLE
Magento Customer Orders Broken

### ISSUE THREAD

**Issue by mikeshiek** [mailchimp/mc-magento#1022]
**Preconditions**
Mailchimp module 1.1.17
Magento 1.14.2.2

**Steps to reproduce**
1. Enable Ecommerce in mailchimp configuration
2. go to a customer record
3. click "orders" on the left side, or "recent orders" accordion tab below

**Expected result**
You should be able to see the customers orders

**Actual result**
1. When "orders" on the left is clicked you get the orange magento load symbol, then nothing happens.
2. When you click "recent orders" accordion tab you get a page that says error has occurred and then it sends you to the magento dashboard (see screen shot).
![Capture](https://user-images.githubusercontent.com/45823543/62472520-7dff3280-b764-11e9-949a-308d0aaf51e5.PNG)

**Comment by gonzaloebiz** [comment]
Hi @mikeshiek 

can you share the file var/report/656038702613 please

Best

**Comment by mikeshiek** [comment]
Yep.

[656038702613.zip](https://github.com/mailchimp/mc-magento/files/3468084/656038702613.zip)

**Comment by mikeshiek** [comment]
I should also mention I had this problem with v 1.1.16. I was hoping it had been fixed in v 1.1.17.

**Comment by gonzaloebiz** [comment]
Please, verify that you have the column mailchimp_synced_flag in the table mailchimp_synced_flag

In other hand, looks like you have a customization in the customer/orders entry, because we don't touch it.
Try to look at app/code/core/Mage/Adminhtml/Block/Customer/Edit/Tab/View/Orders.php(60): Mage_Adminhtml_Block_Widget_Grid->_prepareCollection()

Best

**Comment by mikeshiek** [comment]
Thanks for the info. We found the issue and was able to resolve it.

**Comment by gonzaloebiz** [comment]
You are welcome
