### ISSUE TITLE
Invalid API Key, even if API key is correct

### ISSUE THREAD

**Issue by bargainhardware** [mailchimp/mc-magento#1184]
### Preconditions

1. Magento CE v1.9.4.5
2. Mailchimp for Magento v1.1.20 (same result with .19/.18/.17)

### Steps to reproduce

1. Go to Mandrill settings in Magento.
2. Input valid API key.
3. Save configuration.

### Expected result

1. We should see the account info related to the API key.

### Actual result

1. A message is returned: --- Invalid API KEY ---

I tested this case on v1.1.16 to v1.1.20 and so far v1.1.16 is the last release where this error does not occur. I upgraded to v1.1.20 from v1.1.16 as our orders remained always "In Queue" for mailchimp sync (fixed in v1.1.20) but noticed that we received the error explained above so reverted to each earlier release until we got back to v1.1.16 where it was working again.

**Comment by sudotrin** [comment]
I can only get it to work in Firefox. Doing it in Chrome fails.

**Comment by Santiagoebizmarts** [comment]
Hello @sudotrin 

This is probably because you have a saved password for your Magento admin panel that is overwritting the Api Key value.
We have seen this confusing several people.

I can confirm this works okay for me in chrome so I assume the problem is the one stated above.

In case you still experience problems you can contact our support at mailchimp@ebizmarts-desk.zendesk.com

Kind Regards.
