### ISSUE TITLE
Abandoned cart with configurable products

### ISSUE THREAD

**Issue by MelissaEbizmarts** [mailchimp/mc-magento#153]
When a configurable product is left in a cart, the abandoned cart email send the price range not the price selected when the product was added to the cart.
![image001](https://cloud.githubusercontent.com/assets/23635187/23551664/9065a1c0-fff6-11e6-9ff3-0240f8ad7189.jpg)

**Comment by Simon9311** [comment]
Hi there,

I noticed this issue in my account too. When I place an abandoned cart on my e-store, product were pulled from Magento with the price range and is not showing the right price assigned to the store view.
It happens because we've set as default value 99.999 EUR price while the right prices are insert for each storeview. So it seems that were pulled the right prices with the default value price to Mailchimp.

Is there a workaround to fix this? For example exclude the price placed in the default value view and just pull the storeview's prices?

**Comment by Santiagoebizmarts** [comment]
@Simon9311 
The price is fetched from the child selected in the cart. If this continues to happen with version 1.1.8 we can re-open this issue.

**Comment by thetrybe** [comment]
This is happening again in the latest version 1.0.32
![download 1](https://user-images.githubusercontent.com/47203732/52032727-4fff2280-2576-11e9-8544-53bb7d386e2e.png)
![download](https://user-images.githubusercontent.com/47203732/52032728-5097b900-2576-11e9-9813-7b1bfc33960e.png)

Why was the fix not implemented in the latest version?

**Comment by gonzaloebiz** [comment]
Hi @thetrybe 

wrong repository, please put the comment in the right one

Best
