### ISSUE TITLE
Move debug scripts

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento#155]
Take a look at https://github.com/mailchimp/mc-magento/pull/154

**Comment by Swahjak** [comment]
> The cause of the problem, is that Magento don't have a mechanism to put scripts that should be not executed via web and should have it (Magento 2 have it, but not Magento 1)

Thinking about this. These are both meant as CLI scripts right? Why not move them to shell/ and make them 'proper Magento' shell scripts? (By extending Mage_Shell_Abstract like https://github.com/magento-hackathon/AsyncIndex/blob/master/shell/hackathon_async_index.php). This would fix the security issue since the shell/ directory should be protected by default (there is a .htaccess by default in shell / Mage_Shell_Abstract has a protection against not being executed from cli) and it would also remove the scripts from the root directory.

**Comment by gonzaloebiz** [comment]
Move it to the shell directory sound like a good solution.
In order to make it a proper Magento shell script is more difficult, keep in mind 2 things
* the shell script use the power of the shell and do the things easily
* we include in the last version the possibility of download a response file from the error grid

But we will go to study the issue

Thanks @Swahjak

**Comment by ihor-sviziev** [comment]
Thank you for fixing this issue. Hope you will include these changes to next release.
