### ISSUE TITLE
Stripe payment method: MailChimp Error

### ISSUE THREAD

**Issue by studio2f** [mailchimp/mc-magento#178]
We just switched from using PayPal PayFlow Pro to Stripe as our credit card gateway. After switching to Stripe, ecommerce data stopped being transferred the Mailchimp. Investigating, I've discovered that  Mailchimp_Errors.log is full of hundreds of this error:

2017-03-22T17:40:04+00:00 DEBUG (7): The requested Payment Method is not available.
2017-03-22T17:40:04+00:00 DEBUG (7): The requested Payment Method is not available.
2017-03-22T17:40:05+00:00 DEBUG (7): The requested Payment Method is not available.

The Stripe module we installed is this one:  https://www.magentocommerce.com/magento-connect/stripe-2-20742.html

**Comment by Santiagoebizmarts** [comment]
Hello @studio2f 

When retrieving the order information the payment method seems to fail, this is caused due to the change on the payment and will send new order correctly once the process gets to them. Magento itself is the one throwing that exception. You can add a filter to the date at the ecommerce section in the configuration to avoid old orders.

Please read our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) before creating an issue next time.

Regards.
