### ISSUE TITLE
Major issues with the cronjobs 

### ISSUE THREAD

**Issue by postadelmaga** [mailchimp/mc-magento#182]
We are using _Ebizmarts_MailChimp_ ver 1.1.5 installed few days ago.

Yesterday our server crashed and I think that happened because of the following issue.

### 1. _mailchimp_bulksync_data_ cronjob take about 12 min to be executed 
this make other job to be skipped ( note our server is private and has 8 core + 64GB ram )

### 2. _MailChimp_Errors.log_   shows the following kind of messages :

```
 Resource Not Found for Api Call: batches/b8c771e284 - The requested resource could not be found.

 The requested Payment Method is not available.

 Bad Request : We were unable to process the request. A product with the provided ID already exists in the account.
```

### 3. _system.log_ keep growing (+200mb after few days) and shows the following kind of messages:

```
 Warning: rmdir(/var/www/clients/client2/web3/web/var/mailchimp/b8c771e284): Directory not empty  in /var/www/clients/client2/web3/web/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php on line 60

Error with a response: The requested Payment Method is not available.

Warning: mkdir(): File exists  in /var/www/clients/client2/web3/web/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php on line 245
```

### 4. Folder _/var/mailchimp_ is full of directory and keep growing.

I would appreciate some help here to track down what is causing the above problems.

Thanks

**Comment by Santiagoebizmarts** [comment]
Hello @postadelmaga 

Thanks for the feedback.
There is an item type (Order, Customer, Cart, Product) that is causing the process to stop. This is usually caused due to a conflict with another extension.

With the new version 1.1.6 you will probably avoid that error.
I suggest you to update the extension and clear the var/mailchimp folder, please note this folder needs to exists but it should be empty. Make sure it has the correct write permissions.

If you still have this problem with version 1.1.6 we can reopen this issue.

**Comment by postadelmaga** [comment]
looks 1.1.6 solved the above issues.
Thanks

**Comment by gonzaloebiz** [comment]
Hi @prabhat4 

this place is to put issues about the mailchimp4magento extension, not for general API questions.
If you have questions about how to use the MailChimp API perhaps [this place](https://github.com/mailchimp/APIv3-examples) is the right one, or look at the [offical API documentation](https://developer.mailchimp.com/documentation/mailchimp/reference/overview/)

Best
