### ISSUE TITLE
Webhook doesn't support multi-store

### ISSUE THREAD

**Issue by themystery1** [mailchimp/mc-magento#196]
**Step to reproduce:**
1. Go to first website ( Store1 ) and create a user
2. Subscribe this user to the newsletter ( ListOfStore1 )
3. Go the another website ( Store2 )
4. Subscribe the **same email** as a guest to the newsletter ( ListOfStore2 )
5. Go the MailChimp admin and unsubscribe guest email from step4 ( ListOfStore2 )

**Actual result:**
User from Store1 will be unsubscribed

**Expected result**
Guest subscriber should be unsubscribed from ListOfStore2

_Note: loadByEmail() from ProcessWebhook doesn`t aware the listId and storeId from request

**Comment by TroyPatteson** [comment]
The web hook URL registered in Mailchimp is incorrect as well because the URL generated in the observer function _createWebhook() gets the URL of the default store view. You can see this by logging in to mailchimp and viewing the web hooks for the list.

We fixed this by replacing:

```
protected function _createWebhook($listId, $scopeId, $scope)
{
        $store = Mage::app()->getDefaultStoreView();
```

with

```
protected function _createWebhook($listId, $scopeId, $scope)
{
        if ($scope == 'websites')
            $store = Mage::app()->getWebsite($scopeId)->getDefaultStore();
        elseif ($scope = 'stores')
            $store = Mage::app()->getStore($scopeId);
        else
            $store = Mage::app()->getDefaultStoreView();
```

The thing about loadByEmail() is that is what core Magento does. Quite incredibly, core Magento doesn't support multi-store newsletter by default meaning that if a customer registered on one store then registers with the same email address on another store, the newsletter subscription record is simply overwritten with the new store essentially removing the customer from the old store. This can be fixed with this trivial extension: https://www.magentocommerce.com/magento-connect/multistore-newsletter-subscription.html

The Ebizmarts_Mailchimp extension should definitely be modified so that web hooks fully support mutli-store and therefore work properly with that Netgo_MultistoreNewsletter extension listed above which just fixes what should have been in core Magento in the first place.
