### ISSUE TITLE
Ecommerce order confirmation automations not working with 1.1.6

### ISSUE THREAD

**Issue by jimains** [mailchimp/mc-magento#200]
## Issue Description
I installed 1.1.6 but it doesn't seem to be syncing the store to Mailchimp (see screenshot). It also now won't allow me to save products in the admin either.

### Preconditions
Magento CE 1.9.3.2
mc-magento 1.1.6
Ecommerce enabled in Mailchimp module
Single store configured in Magento
Order notifications enabled in Mailchimp

### Steps to reproduce
Try and trigger an automated order notification in Mailchimp by placing any Magento order
Review status in of automated notification in Mailchimp
Review error logs

### Actual and Expected result
Expected result:
Order is placed and Mailchimp triggers an automated order confirmation
Mailchimp shows that the store is connected when ecommerce is enabled in the Magento module

Actual result:
Mailchimp shows: Store is not connected
No order confirmation is triggered

### Additional information
Product saving doesn't work since installing the module. Possible duplicate of #188

**Comment by Santiagoebizmarts** [comment]
Hello @jimains 

Are you getting any data sent to MailChimp?
Please note that the initial synchronization must finish in order to get the email notifications working.
You can check this at going to [https://us1.api.mailchimp.com/playground/](https://us1.api.mailchimp.com/playground/)
1. Paste your API Key there and click "Go".
2. Click the Ecommerce link.
3. Go to the top right dropdown that says "Subresources" and select "stores".
4. Select your current store and see if the value is_syncing is set to true of false, must be false if you want to receive the notifications.

Regards.

**Comment by centerax** [comment]
@jimains please test the new version and feel free to comment here and we will reopen.-

**Comment by rohan5894** [comment]
Hi,

I am facing the same issue, Extension is installed and Syncing is finished. Now i am trying to receive the Order notification from MailChimp but no luck. 
In the reports it is showing no Orders as well. I have placed many test order but not receiving the Emails.
Can anyone please help?

I am using Magento 1.9.2.4 and MailChimp 1.1.8
