### ISSUE TITLE
max_user_connections exceeded when cron is run

### ISSUE THREAD

**Issue by CMeldgaard** [mailchimp/mc-magento#210]
Have installed the latest version of the module, but everytime it runs the cronjob, it exceeds the max_user_connections to the database, which means customers risk getting an error page on the frontend.

This is the systemlog thats generated of the error:
```
a:5:{i:0;s:106:"SQLSTATE[HY000] [1226] User '******' has exceeded the 'max_user_connections' resource (current value: 20)";i:1;s:1602:"#0 /var/www/hike.dk/public_html/lib/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 /var/www/hike.dk/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(320): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 /var/www/hike.dk/public_html/lib/Zend/Db/Adapter/Abstract.php(460): Varien_Db_Adapter_Pdo_Mysql->_connect()
#3 /var/www/hike.dk/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SET NAMES utf8', Array)
#4 /var/www/hike.dk/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8', Array)
#5 /var/www/hike.dk/public_html/app/code/core/Mage/Core/Model/Resource.php(179): Varien_Db_Adapter_Pdo_Mysql->query('SET NAMES utf8')
#6 /var/www/hike.dk/public_html/app/code/core/Mage/Core/Model/Resource.php(110): Mage_Core_Model_Resource->_newConnection('pdo_mysql', Object(Mage_Core_Model_Config_Element))
#7 /var/www/hike.dk/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(141): Mage_Core_Model_Resource->getConnection('core_setup')
#8 /var/www/hike.dk/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(234): Mage_Core_Model_Resource_Setup->__construct('core_setup')
#9 /var/www/hike.dk/public_html/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#10 /var/www/hike.dk/public_html/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#11 /var/www/hike.dk/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /var/www/hike.dk/public_html/index.php(87): Mage::run('', 'store')
#13 {main}";s:3:"url";s:47:"/mailchimp/webhook/index/wkey/f0f608f8dbf1c41d/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}
```

Been in contact with hosting company, and they can see that in one day mailchimp made more than 25.000 POST request to the website. And its the same webhook url all the time.

Some of the calls return 200 other returning 503.

This means im getting around 15-30 error reports in var/reports every 5min.

**Comment by Santiagoebizmarts** [comment]
Hello,

Thanks for your feedback.
Can you tell me if you are using a multi-store instance of Magento? How many stores?
Are you sure this error shows up after the cron job runs?

I suspect this might be related to movement in your MailChimp list. Whenever a change is made in MailChimp a webhook to your site is triggered to sync back the data altered in MailChimp.
An easy way to prevent this is disabling the **two way sync** and deleting the webhook from your list at [MailChimp.com](MailChimp.com).

It might affect your Magento not having subscriber data up to date but will not affect any of the MailChimp features.

Regards,

**Comment by TroyPatteson** [comment]
We saw a similar issue on our magento store with over 100,000 subscribers and orders. We tracked this down to the database query required to get the last date of purchase called as part of generating the merge variables when processing the subscribe webhook event during the initial two-way sync. (See _getLastDateOfPurchase()_ in the helper).

The issue is that _getLastDateOfPurchase()_ queries the _sales_flat_order_ table by _customer_email_. Unfortunately core Magento does not provide an index on _customer_email_ even though orders can be searched via customer email from the admin pages. As a result the query requires a full table scan which ultimately overloaded our 32-core DB server with 100 GB mysql buffer pool...

The answer is to manually create an index on _customer_email_ for the _sales_flat_order_ table using a query like:

```
ALTER TABLE `<dbname>`.`<table_prefix>sales_flat_order`  ADD INDEX `IDX_OZSS_SALES_FLAT_ORDER_CUSTOMER_EMAIL` USING BTREE (`customer_email` ASC);
```

where  **< dbname>** is your database name and **<table_prefix>** is your database table prefix as specified in _app/etc/local.xml_.
