### ISSUE TITLE
Please SYNC merge data also from past customers - back in the future

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#305]
We have run Magemonkey for years
Then switched to M4M (because you forced us  .... ;)
Now I see that all the merge fields in M4M populate nicely for the NEW orders (after installation date)
But all orders from the past from Magemonkey: did not have the same merge field; or the field is blank
Why does M4M not also populate ALL CUSTOMER data from day 1 according to the new M4M scheme?
Please create this possibility

![image](https://user-images.githubusercontent.com/652395/26894766-b0e3e424-4bbf-11e7-93df-039b815818e1.png)

**Comment by seansan** [comment]
Is this still an issue? or does it backwards populate missing data on old orders too?

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Sorry about the delay on this response. For subscribers the fields I see in the screenshot should be sent properly now.
I am not sure what you mean with order fields. Which ones are not being sent?

Regards.

**Comment by seansan** [comment]
​In a version long before we saw that all kinds of data (that was matched
in backend) -- was not sent over for older orders. For new orders it worked
fine, it just did not fill in the blanks of new fields that are mapped. We
moved from magemonkey and m4m sends a lot more data. The ​orders sent from
magemonkey had less data then sent later via m4m. Mayeb this works fine
now. I can test also. But just asking for an update on the issue.


On Thu, Oct 19, 2017 at 4:53 PM, Santiagoebizmarts <notifications@github.com

**Comment by Santiagoebizmarts** [comment]
@seansan 

I see, maybe you mean that the old orders are not sent as associated to your MailChimp campaigns. Unfortunately this is expected to happen because MageMonkey did not save the campaign info at Magento and due to the API version change on MailChimp the old orders could not be maintained and needed to be resent causing the loss of the campaign info.
MailChimp for Magento does save the campaign data so this will not happen in future changes.

If you find any of this happening with the latest version of the extension we can re-open this issue and address the problem.

Kind Regards.
