### ISSUE TITLE
Please inlcude a INSTALL and UPGRADE guide to every release

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#307]
Please inlcude a INSTALL and UPGRADE guido to every release

3 options
- upgrade from M4M X to Y
- upgrade from MageMonkey to M4M Y
- clean install

This procedure needs to be logged, completed and tested. It is 2017. Things with M4M can no longer go rong because of silly upgrade processes or information that was not known ... .

please! it helps a lot

(and also makes your team aware of the different paths that users fo this SW come from)

![image](https://user-images.githubusercontent.com/652395/26895342-98681260-4bc1-11e7-9e57-3dd3a4daf81a.png)

**Comment by ebizmarts-keller** [comment]
Hello, 

The clean installation is like with any other extension, you just have to add the folders to the Magento root folder merging them with the existing ones, and flush the cache.

The process to go from MageMonkey to Mailchimp for Magento is explained clearly in the Mailchimp FAQ here: http://kb.mailchimp.com/integrations/e-commerce/connect-or-disconnect-mailchimp-for-magento

Upgrading from an old version of Mailchimp to a new one does not differ much from a clean installation, version 1.1.6 includes a change on the schema that requires a migration, but this process is automatic, the cronjobs just need to be working of course, but if they don't no version of the extension would work in the first place, old or new.

We can try do add some new information on the README file but there really isn't that much more to add, I'll look into it, perhaps I will add some links like the Mailchimp guide to migrate from MageMonkey, that guide is pretty clear, it has screenshots and all the necessary steps explained.

Problems with missing tables because of the script are generally not because of an error of the user and need to be looked at case by case, when for some reason the script fails to create a table or attribute there isn't much more choice than creating the table or attribute manually, for which often clients send support requests and we tell them how to fix it depending on what's missing on the database, it isn't really something to include on the readme because every case is different and requires some debugging.
