### ISSUE TITLE
Why does this method exist?

### ISSUE THREAD

**Issue by yoosefi** [mailchimp/mc-magento#322]
`app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php`

```php
protected function returnZeroIfNull($value)
    {
        $returnValue = $value;
        if ($value === null) {
            $returnValue = 0;
        }

        return $returnValue;
    }
```

Really, guys?

I feel like this method perfectly embodies the experience level of the developers and why there are so many bugs in this module.

`isset($value)?$value:0`

Bug filed for code bloat.

**Comment by centerax** [comment]
Its coded that way for clarity.
The ternary operator is not clear enough in my opinion.

By the way, for your future complex expert developer projects, I would check the [PHP documentation](https://secure.php.net/isset) on `isset` since it can have unexpected results depending on the input.
Also, it is a good practice to have blank spaces, again, for clarity. I would change your minimal solution to something like this: `isset($value) ? $value : 0`
