### ISSUE TITLE
Orders not appearing in Magento Admin

### ISSUE THREAD

**Issue by urifoox** [mailchimp/mc-magento#371]
Hello,

It appears that if this extension is enabled, sometimes when an order is placed, payment is captured but there is no record of the order in Magento. We have observed that this only occurs when this module is enabled and seems to be primarily affecting PayPal payment methods. Are there any parts of the code which can trigger an exception that will cause an uncaught fatal error and prevent the order completion process from happening correctly? We believe that sometimes this fatal error also prevents the customer account from being properly registered.

Has anyone observed anything like this or have any suggestions as to where we could isolate the error?

**Comment by Santiagoebizmarts** [comment]
Hello @urifoox 

Thanks for your feedback. Do you see an error on the MailChimp_Errors.log file mentioning a deadlock? There is a known issue that might be causing some orders to fail.

Regards,

**Comment by urifoox** [comment]
Hi @Santiagoebizmarts,

Thanks for the quick reply. Unfortunately the merchants that were impacted by this did not have Debug mode enabled so I do not have that information. As of this morning we have added try/catch blocks to MailChimp/Model/Observer.php in hopes of capturing these exceptions through our central logging. You can review the change at https://bitbucket.org/zoeycommerce/zoey-developer-network-ebizmarts/pull-requests/10/zpd-5993-added-try-catch-blocks-to-the/diff (login as the appropriate user) and backport it into your mainstream branch if you find them helpful. For now, we will keep an eye for any exceptions and update this thread if we find any.

**Comment by Santiagoebizmarts** [comment]
Hello,

This seems a lot like the problem you described, I think we can assume it is. I suggest you to try [this fix](https://github.com/mailchimp/mc-magento/commit/d9278dea3ba9ab1e0a04254a5ca2db181f9ceff1) in order to see if it solves the problem.
Please note that the index will not be created because the version 1.1.8 has not been released yet so the query needs to be run directly in the database console.

**ALTER TABLE `mailchimp_ecommerce_sync_data` ADD INDEX `batch_id` (`batch_id`);**
Prefixes must be added if exists.

If it does not fix it we can re-open this thread.

Regards.
