### ISSUE TITLE
Sync all products before syncing orders

### ISSUE THREAD

**Issue by lfolco** [mailchimp/mc-magento#399]
The way the syncing is combined causes the extension to send a batch of customers, a batch of products, a batch of orders, etc. But we're running into issues where orders are being sent before the products they contain are synced.

Is it possible to always sync products first? Otherwise you have to reset all local errors in order to resync, which due to all the other syncing issues, will cause another lag in getting data to MailChimp.

**Comment by Santiagoebizmarts** [comment]
Hello @lfolco 

Thanks for contacting us.
This issue is caused due to other errors. The order is not sent unless the products contained within are marked as sent.
Seems like there are products that failed to be sent.

Since version 1.1.7 there is a fix to prevent this from happening, unfortunately products that failed before updating to this version will remain with the incorrect mark.

One solution is to mark all the products to be re-sent.
This can be done running the following query in your database console:
**DELETE FROM mailchimp_ecommerce_sync_data WHERE type='PRO';**

In case this is not what's happening to you we can re-open this ticket.

Regards.

**Comment by lfolco** [comment]
That worked, thanks!

**Comment by Santiagoebizmarts** [comment]
Glad to hear!
