### ISSUE TITLE
Order comments email not working

### ISSUE THREAD

**Issue by jorgb90** [mailchimp/mc-magento#409]
When adding order comments and check the send email box it gives a log api call in Mandrill_Request.log but the actual email doesn't get send. The request is also on storeid 0 while other emails are send under storeid 1. Don't know if that makes a difference.

**Comment by Santiagoebizmarts** [comment]
Hello @jorgb90 

Thanks for reaching us. Please add the missing information in order to allow us to test this in the same scenario you are.
You can read all the information necessary for an issue in our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines).

Kind Regards.
