### ISSUE TITLE
Unsubscribing user from newsletter in admin does not get updated in MailChimp

### ISSUE THREAD

**Issue by samgranger** [mailchimp/mc-magento#433]
Unsubscribing users from the newsletter subscription grid in the admin does not update user in MailChimp.

**Comment by Santiagoebizmarts** [comment]
@samgranger Thanks for your feedback, I will get back with a solution shortly.

Regards.

**Comment by Santiagoebizmarts** [comment]
Hello @samgranger 
This feature works okay in my tests. Please note that the subscription is not handled automatically, the data is sent in the next batch so it might take up to 5 minutes to send the data.

If this happens please add more information about the issue in order to reopen it.
You can see the information required to open an issue [here](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines).

Regards.
