### ISSUE TITLE
Order status not updated in Mailchimp

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento#481]
mc-magento 1.1.8-1.1.8.10
Magento 1.9.3.3

When a order status changes (ie, from Pending to Canceled) in Magento, it will not update the status in Mailchimp.

This is because **mailchimp_sync_modified** doesn't change to 1 when the order status in changed from Magento in the table **mailchimp_ecommerce_sync_data**, if changed manually it works.

**Comment by Santiagoebizmarts** [comment]
Note: Only happens when extension configured in particular store view.

**Comment by ljay79** [comment]
Hi. Apparently this fix never made it into any release yet.
Even it indicates here its been included in release 1.1.10 and 1.1.12, when i checked the source code, it is not there.

Has this been replaced by another fix?
Because i do expirience the issue with Order status not been updated on Mailchimp.

1. Order gets placed during one-page checkout
2. payment fails and sets order into "cancelled"
3. On mailchimp i can see the order for that customer and the revenue increased

Mailchim4Magento 1.1.12
Magento 1.9.3.8 CE

Mailchimp is configured per "Store"!
- Website 1
-- Store A    _<- Mailchimp config A_
---- Store View a1
---- Store View a2
---- Store View a3
- Website 2
-- Store B    _<- Mailchimp config B_
---- Store View b1
---- Store View b2
---- Store View b3

**Comment by ljay79** [comment]
Update:

I was able to verify, that the sample order (cancelled in Magento) has correct status in Mailchimp "financial_status" = "canceled".
So it seems to be an issue on Mailchimp's side when such order is still added to the customers and/or total revenue amount.

Do i miss a setting here?

**Comment by Santiagoebizmarts** [comment]
Hello @ljay79 

You are right, it looks like MailChimp processes the cancelled orders in the same way as the paid ones.
I suggest you to take this issue to MailChimp support.

Kind Regards.

**Comment by seansan** [comment]
Do you have a technical contact Santiago?

**Comment by Santiagoebizmarts** [comment]
https://mailchimp.com/contact/support/index.php

**Comment by ljay79** [comment]
I had a chat with Mailchimp and they could confirm this bug on their end.
Here is the official feedback they provided me.

> My colleague has confirmed that is affected by an issue with syncing cancelled order data that our devs are currently working to resolve.  While I'm not able to offer and ETA for a fix at this time, I can assure you that once we've got a stable solution it will be rolled out to all affected accounts. I've reported this account as being affected by this issue and made note of the issue on our ticket, #4395979.  If you have any questions about this issue moving forward, you can write in or join us in a live chat and reference that ticket number.

- Mailchimp Support advised, other affected Mailchimp customers should report this issue to MC, so their DEVs have the volume in order to prioritize a fix.
- May i suggest to keep this Issue here a little longer "open" so that other affected users can easily find it!?

**Comment by seansan** [comment]
thx @ljay79 - what did you submit exactly I have a good contact there and can shoot it in too


NB> I always find this strange `other affected Mailchimp customers should report this issue to MC, so their DEVs have the volume in order to prioritize a fix` - if ti is a bug then fix it. Not everything should depend on the number of requestors
