### ISSUE TITLE
Invalid Resource Error

### ISSUE THREAD

**Issue by infabo** [mailchimp/mc-magento#497]
mailchimp_errors table

> "http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/"
> "Invalid Resource"
> "400"
> "merge_fields.BILLING : Data did not match any of the schemas described in anyOf. / merge_fields.SHIPPING : Data did not match any of the schemas described in anyOf."
> "SUB"

**Comment by Santiagoebizmarts** [comment]
Hello @infabo 

Please follow our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) before reporting a new issue.

Also please note we have seen this error before and it should be fixed in the latest version.
The only case we were not able to solve was when MailChimp considers a filed required in the address but Magento don't. For example the post code, in some cases the missing post code in Magento causes this error because MailChimp requires this field in order to add an address.
From the extension side of things there is nothing we can do for this last case.

Regards.

**Comment by infabo** [comment]
Hello @Santiagoebizmarts 

maybe you should log some more relevant data like cusomer id for example. then i would be able to post some more relevant data like "oh, seems like the issue is, that the customer account has no addresses at all" for a good example.

and already using the latest version, 1.1.9, and the log table is full of these messages (truncated table before).

**Comment by Flipmediaco** [comment]
@infabo I agree! No way of tracing the error, when it was created and the "Download" link downloads an empty json file. Kinda pointless logging function!
