### ISSUE TITLE
Optimizations - Inline JS?

### ISSUE THREAD

**Issue by andresinspace** [mailchimp/mc-magento#525]
helper/data.php - getMCJs() method

Responsible for returning script tag with source url:
https://chimpstatic.com/mcjs-connected/js/users/####.js
 
I've looked at both my sites and the script it calls is only returning some very short simple JS..
`(function(){if(!window.$mcSite){$mcSite={};}})();`

Can't this just be inlined to avoid blocking and an extra resource request?

**Comment by Santiagoebizmarts** [comment]
Hello @andresinspace 

This is something MailChimp is currently working on. The js file will include some new features soon.

Kind Regards.

**Comment by dan-ding** [comment]
What is this script even for?

**Comment by dbashyal** [comment]
I had to add 'async defer' to this script as it was blocking page load.

**Comment by AndresInSpace** [comment]
Reopening this because it's nearly two years later and this script still returns the same tiny bit of JS...
Still don't understand what it's used for; as far as I can see $mcSite variable is not referenced in repo code anywhere.
`(function(){if(!window.$mcSite){$mcSite={};}})();
`
I've since modified the getMCJs() function to inline this JS instead of sending out a request for it. 
`return '(function(){if(!window.$mcSite){$mcSite={};}})();';`
