### ISSUE TITLE
Tier prices being deleted after products being sent.

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#57]

**Comment by jorgb90** [comment]
Just downloaded Master 1.1.1 and this fix isn't included.. Added it myself to products.php but again lost tier prices because of that :(

**Comment by delarosajv** [comment]
What a mess...

i've lost it too :(

@jorgb90 have found another issue? i'm still having problems with the sync and maybe the last update miss another fix..

**Comment by Santiagoebizmarts** [comment]
Hello @jorgb90 and @delarosajv,

Are you sure you have the latest version 1.1.1? This works okay for me. The fix is at [this line](https://github.com/mailchimp/mc-magento/blob/master/app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php#L38).

When loading the product all the attributes such as tier prices and dropdowns are loaded and then saved properly later in the code.
In case you do have the latest version 1.1.1 please tell me what version of Magento do you have installed for me to test it.

**Comment by jorgb90** [comment]
@Santiagoebizmarts Ah ok so you have made another fix for the issue. We are using Magento 1.9.2.4 by adding [this fix](https://github.com/mailchimp/mc-magento/commit/f6e43663904c4156b8659a96517db089a4a85219) manually again in Products.php it worked..

**Comment by Santiagoebizmarts** [comment]
@jorgb90 ,

The other fix is included in version 1.1.1 and works okay for me.
What version of Magento are you using?
Do you have any customizations on your products?

**Comment by jorgb90** [comment]
This is still not solved! When reset somehow fails every attribute is set back to is default value and tier prices will be removed. It only works when the reset does its job correctly..

**Comment by GeekMediaDK** [comment]
I also have this issue. Doesn't the version miss the $product->getTierPrice(); in model>api>products.php 

This was the fix i got for an earlier version.

**Comment by GeekMediaDK** [comment]
@centerax @gonzaloebiz 

Whats the status of this bug?

**Comment by Santiagoebizmarts** [comment]
When loading each product [here](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php#L38), it should also load the tier prices.
I guess we can add this if it keeps happening on some installations.
Can you confirm this keeps happening on the latest version 1.1.2?

**Comment by GeekMediaDK** [comment]
@Santiagoebizmarts 
I've just deleted all my local errors, which keep stacking up:
 - We were unable to process the request. An order with the provided ID already exists in the account.
 - We were unable to process the request. A product with the provided ID already exists in the account.
 - A product with the provided ID does not exist in the account for this list.
 - customer : Required fields were not provided: id / customer.id : Schema describes string, NULL found instead
 - CGROUP : Value must be one of: General, Wholesale, Retailer, tilbud, NOT LOGGED IN (not Dansk forbruger)

And not it just dropped 200 tier prices!!! So there is not pattern to it, because is synced 844 products without any problems, and then i just deleted the local errors which then deleted 200 tier prices. Could this happen, if someone reindexes during syncronisation?

**Comment by Santiagoebizmarts** [comment]
Hello,
I've added the getTierPrice function to avoid this particular scenarios.
You can see the solution in the commit referenced above.

Thanks for your feedback.
