### ISSUE TITLE
No Product Images

### ISSUE THREAD

**Issue by domb182** [mailchimp/mc-magento#596]
No product images are being sent to Mailchimp.
They are either using cached images that are no longer there or the default mage placeholder image.

Updated to the most recent release of the plugin.

Does anyone else have this issue?

**Comment by ebizmarts-keller** [comment]
Hello @domb182 

We need a little bit more of information to look into this, please follow this guidelines and edit your post: https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines

**Comment by devgeektech** [comment]
Hello @Santiagoebizmarts 

I have a image issue to sync from magento to mailchimp.

we are getting the default image of magento for the product in mailchimp account.

I check this solution
===============
https://github.com/mailchimp/mc-magento/commit/7c4c81655a14e58dd9e3bbe5308da6852b3cf2ae

But it was already correct in my magento extension files.

Please let me know best solutin for this to resolve image sync issue.

Thanks

**Comment by Santiagoebizmarts** [comment]
Hello @devgeektech 

Updating to the latest version should solve this problem.

Regards.

**Comment by devgeektech** [comment]
Hello @Santiagoebizmarts 

I am already using the latest version of ebizmart extension:
Magento v1.1.12 by ebizmarts 


Please let me know if any other best solutions.

**Comment by Santiagoebizmarts** [comment]
@devgeektech In that case there are a couple options that could be happening.
1. Products were sent with a previous version with this problem and need to be updated by clicking the Resend Ecommerce Data button in the configuratioin.
2. There is a conflict with another third party extension.

I suggest you to try the solution 1 and if that does not work contact our support at mailchimp@ebizmarts-desk.zendesk.com
Please note that the product images should start being updated from lower id to higher id therefore you should check the products with lower id numbers in order to see if the solution is working.

Regards.

**Comment by devgeektech** [comment]
@Santiagoebizmarts 

if i will give you setting on my extension then will you able  to help me?
please check the attach snapshot of setting

Products were sent with a previous version with this problem and need to be updated by clicking the Resend Ecommerce Data button in the configuratioin.
==>yes I did it many times but not effect.

![screencapture-fallsriversoap-admin-system_config-edit-section-mailchimp-key-df4a4aa8752f0caca8b872fe64f92430-2018-07-16-21_32_02](https://user-images.githubusercontent.com/21241618/42769557-10f5b8d8-8940-11e8-80dd-2b3d348d08c0.png)

**Comment by devgeektech** [comment]
@Santiagoebizmarts 

I want to discuss with you that i setup this extyension for the : 
"Current Configuration Scope: defult config"
in magento backend...Hope this setting is fine and will working.

Please let me know your review about that too.

**Comment by gonzaloebiz** [comment]
Hi @devgeektech 

please remove this API key urgently and create a new one.

Best

**Comment by Santiagoebizmarts** [comment]
Hello @devgeektech 

As @gonzaloebiz says create a new API key and disable that one because anyone with access to your API key can access to your subscriber data.

About your product image problem, we need to know how your product images are set up. Do you use a CDN?
Does this happen to all the products? Maybe just for configurable?
Do the numbers shown in the screenshot match your Magento data?
Do you have 65 products in your store?

Regards.

**Comment by devgeektech** [comment]
Hello @Santiagoebizmarts 

I deleted my message and snapshot...so it will be fine?


About your product image problem, we need to know how your product images are set up. Do you use a CDN?
==> No I am no using the CDN


Does this happen to all the products? Maybe just for configurable?
==> yes it happen with all products.

Do the numbers shown in the screenshot match your Magento data?
=> Yes its matches

Do you have 65 products in your store?
==>Yes its a 65

Please let me know if you help me.

**Comment by Santiagoebizmarts** [comment]
Hello @devgeektech 
In that case please contact our support at mailchimp@ebizmarts-desk.zendesk.com in order to get more personalized help.

Regards.
