### ISSUE TITLE
Add information how much customers, products, orders, carts are pending sync

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento#600]
Right now we have information how many customers, products, orders, carts are already synced, but it's not clear how much still pending sync, as result for big merchants it's not clear now long will be sync process.
![capture 2018-01-04 at 10 28 09](https://user-images.githubusercontent.com/1873745/34815483-23043cd4-f6ba-11e7-918d-f0ec85b82bac.png)

At least information about "customers" is not trivial to find because it is includes data from orders that was created by guests

**Comment by Santiagoebizmarts** [comment]
Hello @ihor-sviziev 

This makes sense to me. For customers it might not be that easy to tell because as you said there are guests doing purchases as well and they will be sent as customers to MailChimp.
For the rest should be easy to know how many items remain to be processed.

Regards.

**Comment by seansan** [comment]
I think this is very smart to add and adds to closed-loop goal: no data errors or missed data!

+1

Maybe even a separate page

**Comment by Santiagoebizmarts** [comment]
Hello @ihor-sviziev @seansan 

Unfortunately after looking this in more detail we decided not to do it. The reason is that we can not know exactly the amount of items that should be sent.
Since Bundled and Grouped products are not supported, in order to know the amount of orders and carts we would need to look into each one and that is not a viable option.

In order to know how long the initial sync should take in your case please read [THIS](https://ebizmarts.com/forums/topics/view/27463).

Regards.
