### ISSUE TITLE
Initial sync it too slow for big merchants

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento#609]
We deployed mailchimp module to store that have 450000+ orders (most of them - created by guests), 100000+ customers, initial sync running already 1 week and it didn't finished yet. I think it's too much. 

Our configuration:
- Subscriber amount to be sent per run: 1000
- Customer amount to be sent per run: 1000
- Product amount to be sent per run: 1000
- Order amount to be sent per run: 1000

We tried to change these values to smaller and bigger - sync become slower.

When I'm looking to process list in DB  - there are a lot not queries that are getting orders one by one, instead of getting bulks, there are a lot insertions and deletes to mailchimp_ecommerce_sync_data.

Do you  have any recomendations how to improve sync (still in progress at ~70%)

**Comment by Santiagoebizmarts** [comment]
Hello @ihor-sviziev 

Probably the job is taking more than 5 minutes due to large batch limits, therefore in stead of sending 1000 of each every 5 minutes, it sends 1000 of each every 10 minutes or maybe 15 depending on the server capacity. Sometimes the lower number actually increases the speed of the process if you make sure the cron job does not take more than 5 minutes.
I recommend lowering the product batch first because orders will send their unsent products anyways.
Our recommendation is to set the highest number possible maintaining the cron process under 5 minutes.

We are always trying to improve the efficiency of the process, in the next versions it should take even less time.

Another thing to consider is that when the Resend Ecommerce Data button is pressed the cron alternates and send old data in one run and new data in the next causing the process to be slower so it is not recommended to press this before the initial sync finishes.

About orders going one by one, please note we send all the commerce data via bulk batches. This would make sense if you pressed the button mentioned above.

Regards.
