### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by leossmith** [mailchimp/mc-magento#661]
When enabling the extension, it uses enormous amounts of CPU resources. I run the site in a vps with 5 cores and 6.5gb ram, using about 50% of the resources. When we enable the extension, the CPU usage goes up to 99%.

### Preconditions
PHP 5.6
mySQL
Magento 1.9.3.8 ce

### Steps to reproduce

1. Install extension to Magento 1.9.3.x
2. Enable it and connect to Mailchimp
3. See your server explode

### Expected result

1. Usage shouldn't be increased that much

I have tried several versions of this extension, without any results.

**Comment by Santiagoebizmarts** [comment]
Hello @leossmith 

Thanks for contacting us. I suggest you lowering the batch amounts in the configuration.
Do you have a multi-store setup? Enabling it in one store view at a time and waiting for that store to fully sync will help as well.

Please note this only happens when the initial synchronization is going, after the store is fully synced the server usage should decrease.

Please note the latest version has improvements in performance as well.
Let me know how it goes after following this suggestions.

Regards.

**Comment by leossmith** [comment]
Hi there,

I only have one store with about 10k subscribed users. They are already imported in Mailchimp via csv. During the high peak usage, the extension was disabled in the backend. I had to go to the FTP and deactivated to bring the cpu down. The cpu usage was going one for more than 2 days, before finally deactivating the extension. We had the same issue on an earlier version that led us to disable it, and do it manually. We currently have installed version 1.1.10.

**Comment by Santiagoebizmarts** [comment]
Hello @leossmith 

Thanks for your feedback. This makes me wonder if your issue is with having too many webhooks being processed. Please check the amount of entries in the database table **mailchimp_webhook_request**

Also please note we have made changes in version 1.1.11 which is the new latest that improves performance and have more checks to avoid observers from running if the extension is disabled.

Regards.

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

The fix you are talking about has nothing to do with this because the products are not sent if the extension is disabled.
Please try to read more carefully before posting because you can create missunderstandings.

Regards.

**Comment by leossmith** [comment]
There are 103 entries in my mailchimp_webhook_request.

**Comment by Santiagoebizmarts** [comment]
@leossmith Okay in that case I suggest you to try the improvements placed in the latest release 1.1.11 which should not increment any CPU usage when disabled.
For actually using the extension I suggest you to set it up at a low traffic hour in your store and wait for the initial sync to end. You can set low batch amount numbers to decrease the server load.

Then after the initial sync is finished, check how your server runs.

Please note big changes in your MailChimp list might trigger a lot of webhooks to your store causing the server load to increase as well. (i.e.: Unsubscribing, deleting or modifying too many subscribers at once)

Let me know if you still find problems in this test.

Regards.

**Comment by leossmith** [comment]
Thank you. I will try it again. I had tested it during version 1.1.5 release, but the server load never went down and this is why we disabled it. However we need email automation so we need it. I will test during night time, and give you feedback.

**Comment by maronk** [comment]
@Santiagoebizmarts I think this could possibly be related with this one: 

https://github.com/mailchimp/mc-magento/issues/665

We have a fairly large customer base, approx 105K customers and ca 30K active products.  We are seeing that once these 10-15 sec queries run, sometimes other requests (not necessarily related with the m4m extension) will cascade on back of the first one, probably due to table locks etc - so while the m4m extension is not the only cause of the high cpu usage, it is often the trigger of a snowball effect, and during that time if traffic does not slow down it brings the server to a halt.

**Comment by seansan** [comment]
+100

This is exactly what happens. Exact!

And why all these performance issues have to have max urgency like this
issue

#584
#309
#609
#583

It almost becomes un-workable otherwise

**Comment by Santiagoebizmarts** [comment]
Hello @seansan we are adding performance updates in every update. We are testing the extension with stores containing more than 200k products.
Version 1.1.12 is coming very soon, by the end of March probably, with more improvements in this matter.

Regards,

**Comment by bw1984** [comment]
I can also confirm that this is happening on our installation. What we found strange is that the lists seemed to sync fine initially (batch size set to 200), but then the next time we visited the settings screen we received a message telling us that the store had become disconnected. Upon attempting to re-save the existing settings the CPU went through the roof. After several reboots we were still seeing huge spikes, all attributed to scheduler.php (in newrelic) only disabling the module entirely prevented the issue from continuing.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/4680713/38624236-89c2ec50-3d9f-11e8-9767-0ab36f1a64d7.png">

Also we noticed that changing the store/scope seemed to create a huge overhead (not sure of this is related but we attempted this having received the first error regarding the store being disconnected)

Also we have AEO_Scheduler installed to manage all cron activity

Is 1.1.12 on the horizon? i see the version number in /app/code/community/Ebizmarts/MailChimp/etc/config.xml has already been changed...

**Comment by seansan** [comment]
>> Version 1.1.12 is coming very soon, by the end of March probably, with more improvements in this matter.

How is this update from the end of march going?

**Comment by andreasemer** [comment]
I can't see performance relevant code in the diff of 1.1.11 to 1.1.12 Can you please give me a hint where to find this described performance optimisations?

**Comment by gonzaloebiz** [comment]
Hi @andreasemer 

you can see detailed changelog at https://github.com/mailchimp/mc-magento/releases

Best

**Comment by andreasemer** [comment]
Hello @gonzaloebiz thank you very much for this hint, i have already seen the changelog and checked the diff. I don't see any performance optimisations ;-)

**Comment by AndresInSpace** [comment]
Has this been addressed in any of the releases to date? 1.1.14 latest release atm

**Comment by Santiagoebizmarts** [comment]
Hello @AndresInSpace 
We are constantly adding improvements to the performance.
When first installed, if the ecommerce data is enabled, all the information of the store will be sent to Mailchimp. That might increase the CPU usage but there are recommendations to avoid this.
We did not have any new report in the latest version 1.1.14 so far.

### **Recommendations**
1. **Set the batches amount to a minimum**. Even in 50 you should get 600 items of each object sent every hour, this means you can have more than 14000 of each item type per day, this is around 60000 items sent per day.
2. **Use the filter dates for orders and carts**. Very old orders are usually not necessary.
Old carts are definitely not wanted since Cart automations only make sense for recently abandoned carts.
3. **Enable one store at a time**. For multi-store instances, it is best to enable one store view at a time, wait until it fully syncs and then enable the next one.
4. **Enable Carts and Promo Codes after the initial sync finishes**. In case the above are not enough, Carts and Promo codes can remain disabled and only enable it after all the other items were sent.
