### ISSUE TITLE
Request: add ability to send the actual BRAND/Manufacturer in the Vendor field

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#672]
Request: add ability to send the actual BRAND/Manufacturer in the Vendor field

Now it contains 1 category name or id?

### Expected result
Filter customer product recommendations for 1 brand

### Actual result
Can filter by 1 category (a product may exist in many categories)

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Thanks for your post.
The problem with this is that the Category automation uses this field to know the category of the product.
MailChimp does not provide a place to add the manufacturer. After giving some thoughts to this and talking with MailChimp devs, we arrived to the conclusion that the best way to approach this at the moment is sending that info in the type field. I will reference this once it gets added.

Regards.

**Comment by seansan** [comment]
Thanks

We also spoke to MC. And I think the long term better way to go is to add a
field for brand and product type in the api

But sounds great for a short term solution

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

After more conversation with MailChimp we got to a point where the type field will not meet your needs because you cannot filter a campaign based on that field.
The only alternative they provided is to manually add each product in a multiple criteria campaign. You would only have to do this once and then copy the campaign and add the new products as they are created in the store.

I know this is not a good solution for large stores but unfortunately is the only one with could come up with the current API.

Regards.

**Comment by seansan** [comment]
thanks

maybe also give the faadback that they should "add some more fields in the
API" and after that in the "Products Block" in the editor to filter by it

On Tue, Mar 20, 2018 at 2:32 PM, Santiagoebizmarts <notifications@github.com
