### ISSUE TITLE
Not correct email show bcc mail in "to"

### ISSUE THREAD

**Issue by shariqshahab** [mailchimp/mc-magento#694]
In mail "to" show "bcc" email 

![screenshort](https://user-images.githubusercontent.com/11956324/38915681-fcdc8a9e-42fd-11e8-9301-812383c6c5ff.png)

**Comment by ebizmarts-keller** [comment]
Hello @shariqshahab 

The way you explain the issue I don't see the problem, if you could perhaps clarify what you think the issue is.

What I see in your screenshot, is that a copy of the order confirmation was sent to your bcc email (this being your gmail address), therefore it is correct to display the bcc email address in your gmail inbox in the "to field", meanwhile in your hotmail inbox you will see your hotmail email address in the "to" field.

There is no "bcc" field for the receiver since this is a **blind** carbon copy of course.

If you have any additional feedback or need further clarification let me know.
