### ISSUE TITLE
Double Opt-In does not work

### ISSUE THREAD

**Issue by receter** [mailchimp/mc-magento#696]
When a new customer registers for an Magento account and chooses to subscribe to the newsletter, he will be added to Mailchimp without receiving a Mailchimp Opt-In E-Mail.

### Preconditions
1. Magento 1.9.3.1
2. Multiple stores (Deutsch, English, Französisch)
3. Customer/Subscription Options/Need to Confirm is set to "Yes"

### Steps to reproduce
1. Create account
2. Subscribe to list with Double Opt-In activated in Mailchimp

### Expected result
1. New Member will get a Double Opt-In Message form Mailchimp before appearing as subscribed in the list.

### Actual result
1. New Member is added to list without having to confirm.

**Comment by Santiagoebizmarts** [comment]
Hello,

This is how Magento works. Since the subscriber is logged in, it does not send confirmation email. It only sends confirmation if the subscriber is not logged in.

Regards.

**Comment by receter** [comment]
@Santiagoebizmarts I understand your point. But as far as I understand the Terms, Mailchimp may suspend my Account if I just add E-Mail-Addresses without having consent.

And in this case, I do not have consent in any way. I may just add random E-Mail-Adresses (in the worst case spam traps) to every List that is connected to any Magento store. 

Would it be possible to make a toggle in the MagentoForMailchimp settings to allow a store owner to be sure Double-Opt-In is triggered in any case where a new E-Mail is added via the Extension?

As far as I remember, iIt did work with the last extension.

**Comment by Santiagoebizmarts** [comment]
Hello,

You do have consent because the customer is actively clicking the button to be subscribed.
You can force the confirmation email by modifying the following files:
https://github.com/mailchimp/mc-magento/blob/dddf4023dfaf132e0e891607921b8e43f57a39ff/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php#L333

Just set that to **$newStatus = 'pending';** and you should be good to go.
I suggest you to test it since it has not been fully tested.

Regards.

**Comment by receter** [comment]
Thanks for your response, I will try that.

And yes, he is clicking the button, but how do I know that he is the owner of the email address? He has not confirmed his identity at the time the email gets send to MC

**Comment by Santiagoebizmarts** [comment]
Account confirmation email is an available in Magento, I guess you should enable that or you might be sending unwanted emails anyways.

Regards.

**Comment by gfxpixeldesigns** [comment]
We are also facing this problem.

Customers may be giving consent at registration by clicking the checkbox but new GDPR laws come in to effect on the 25th and under these new laws its going to much better to have double opt-in. Although technically not required its better to give customers a clear indication that they are signing up for a mailing list. Many customers simply fly through registation ticking anything and everything so a second layer of confirmation (double opt-in via email) is going to confirm with them that they are subscribing to a list and its also going to mean your lists are genuine sign-ups with less chance of complaints.

Please add this as an option so that we can enable double opt-in.
