### ISSUE TITLE
Customer Fields Mapping is not send in Customer E-commerce data

### ISSUE THREAD

**Issue by maximehuran** [mailchimp/mc-magento#699]
### Preconditions
1. Magento 1.9.3.8
2. ebizmarts/mc-magento 1.1.11

### Steps to reproduce
1. Configure some customer fields for mapping
2. Update mapped customer fields
3. Launch `mailchimp_bulksync_ecommerce_data` cron

### Expected result
1. Fields are updated on Mailchimp

### Actual result
1. Fields are not updated in Mailchimp

### More info
It works when I subsribe or unsubscribe to the newsletter front the Magento website.
Because merge vars are called only on subscribers models.

**Comment by Santiagoebizmarts** [comment]
Hello @maximehuran 

[Customers](https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/customers/) do not allow merge fields in the API schema, only [Subscriber](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/) do.

Regards,

**Comment by maximehuran** [comment]
Why not, but what is the utility of the configuration `Subscribe all customers to the newsletter` ?
It's really annoying because we need to synchronize some customer data with Mailchimp.

**Comment by Santiagoebizmarts** [comment]
Hello @maximehuran 
This limitation exists in the MailChimp API schema. The "Subscribe all customers to the newsletter" option allows to send all the customers as subscribers to MailChimp therefore the merge fields of those subscribers will be sent correctly.
The problem is only when sending customers as NOT subscribed.

Regards.
