### ISSUE TITLE
Store creation error when Mailchimp_Error is thrown within system configuration

### ISSUE THREAD

**Issue by andrew-smart** [mailchimp/mc-magento#740]
When simply viewing the configuration in the Magento backend it is possible that the store is recreated because of a general curl error being thrown within the MailChimp library

### Preconditions
1. Magento Version 1.9.3.8
2. Module version 1.1.11

### Steps to reproduce
Keep refreshing the mailchimp system configuration screen

### Expected result
Upon curl error, the store is not re-created but a message about not being able to retrieve the store data is shown.

### Actual result
The mailchimp store is re-created.

In Ebizmarts_MailChimp_Model_System_Config_Source_Account there is a `} catch (MailChimp_Error $e) {` on line 73. This originates from the call on line 59 to get the store data. Following this through to the MailChimp library and the "call" function on line 311 in lib/Ebizmarts/MailChimp.php it is possible that a generic MailChimp_Error is thrown for a curl error. That might simply be a connection issue but the subsequent code in the Account model treats all MailChimp_Error exceptions the same.

Furthermore, the MailChimp_Error exceptions thrown for 4xx codes (line 346) in the library should also not end up recreating the store.

**Comment by Santiagoebizmarts** [comment]
Hello @andrew-smart 

I believe the problem is related to the issue explained in our forum post [HERE](https://ebizmarts.com/forums/topics/view/28025)
In version 1.1.12 we made a change to show the correct message in that particular error.

If this is not the case please elaborate on the exact error or maybe add a screenshot to allow us to reproduce it because I am not being able with the information provided.

Regards.
