### ISSUE TITLE
Consider making promo code batch limit configurable

### ISSUE THREAD

**Issue by Leland** [mailchimp/mc-magento#761]
The limit rates for other aspects of batch data sending are configurable in the admin, but promo codes are fixed at 50:

https://github.com/mailchimp/mc-magento/blob/0f695fc2e9fda9bd6ea93932ddbd6be99872d127/app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php#L14

We're running a store that has literally tens of thousands of auto-generated coupons, meaning that syncing all of them will take a tremendously large amount of time out of box.

Of course, we can override this ourselves, but this should probably be configurable without needing some additional code.

**Comment by Santiagoebizmarts** [comment]
Hello,

As you can see [HERE](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php#L76) in the develop branch there is a change to prevent problems with promo codes.
It will send first the newest rules in order to allow you to have all the latest promo rules and send the old ones at the end.
You can apply that change in your end if this would help you.
Please not that even with this limit set in 50 you will have 14400 promo codes sent per day which are a lot.

The idea is to reduce the amount of configuration settings to a minimum.

Regards.
