### ISSUE TITLE
Feature request - show actual sync progress

### ISSUE THREAD

**Issue by bw1984** [mailchimp/mc-magento#786]
we have the following information available on the module configuration page;

```
Username: ABC123
Total Account Subscribers: 3370
Total List Subscribers: 2994
Ecommerce Data uploaded to MailChimp store ABC123:
Initial sync : In Progress
Total Customers: 377
Total Products: 397
Total Orders: 43
Total Carts: 34
```

but when we have a long period of the sync being 'In progress' it would be helpful for us to be able to see where it is up to with some sort of progress indicator(s). Its impossible to tell from looking at this how much is still remaining

**Comment by ebizmarts-keller** [comment]
Hello @bw1984 

If you compare those numbers you see, with what you actually have in your store (in orders, customers and products grids), you can extrapolate from there how much is there left. 
For example if you know you have 100 orders, and in the totals it says you synced 50, you know how many are left from that. The one that you can't check so easily is the abandoned carts because you can't see abandoned carts from guests in your admin panel and we sync this as well.

The only thing to consider is that certain product types are not compatible and therefore you must take those out of the equation, this being Bundle, Grouped, Gift and Custom type products, and the orders containing this product types as well.

The team will look into your suggestion and evaluate if it is viable as an enhancement anyway.
