### ISSUE TITLE
Use magento's email templates

### ISSUE THREAD

**Issue by ktsixit** [mailchimp/mc-magento#831]
After updating to version 1.1.13, Newsletter confirm subscription email is not sent using magento's default template. Subscribe/Unsubscribe emails are sent though Mailchimp, using mailchimp templates.

### Preconditions
1. Magento 1.9.3.8
2. Mailchimp For Magento v1.1.13

### Steps to reproduce
1. Subscribe to Newsletter

### Expected result
1. Receive "Confirm Subscription" email, using magento's email template. 
2. After confirming Subscription, receive "Thank you for your Subscription" using magento's email template. 

### Actual result
1. Receive "Confirm Subscription" email from mailchimp, ignoring magento's email template.

**Comment by ebizmarts-keller** [comment]
That has always been the module's behavior, it isn't a bug introduced in 1.1.13. Since the module its meant to be used with Mailchimp emails, Magento emails are disabled from the code to avoid duplicated emails.

Nevertheless an option will be added to choose between Magento and Mailchimp emails, in version 1.1.14

**Comment by ktsixit** [comment]
Thank you for your response. Is there any way to disable it temporarily, until 1.1.14 update is published?

**Comment by ebizmarts-keller** [comment]
Send a support request to mailchimp@ebizmarts-desk.zendesk.com
